/*
 * generated by asking google:
 * "reusable react MUI component that can be embedded in signup and change password forms to take two passwords, validate that they match, and contain a configurable number of upper case, lower case, digit and special characters"
 */

/* NOT as flexible as Django https://docs.djangoproject.com/en/dev/ref/settings/#auth-password-validators */

import React, { useState, useEffect } from 'react';
import {
  TextField,
  IconButton,
  InputAdornment,
  Box,
  Typography,
  List,
  ListItem,
  ListItemIcon
} from '@mui/material';
import {
  Visibility,
  VisibilityOff,
  CheckCircle,
  Cancel
} from '@mui/icons-material';

export default function MatchingPasswords({
  onChange,
  // these CAN be supplied for each use, but better to change them
  // HERE, so the same settings apply to both SignUp and ResetPassword
  // uses.
  minUpper = 1,
  minLower = 1,
  minDigits = 1,
  minSpecial = 1,
  minLength = 8,
  labels = {
    password: "Password",
    confirmPassword: "Confirm Password"
  }
}) {
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);

  // Track validation status
  const [status, setStatus] = useState({
    hasUpper: false,
    hasLower: false,
    hasDigit: false,
    hasSpecial: false,
    hasLength: false,
    matches: false,
    isValid: false
  });

  useEffect(() => {
    // Count occurrences using regex matches or default to 0
    const upperCount = (password.match(/[A-Z]/g) || []).length;
    const lowerCount = (password.match(/[a-z]/g) || []).length;
    const digitCount = (password.match(/[0-9]/g) || []).length;
    const specialCount = (password.match(/[^A-Za-z0-9]/g) || []).length;

    const checks = {
      hasUpper: upperCount >= minUpper,
      hasLower: lowerCount >= minLower,
      hasDigit: digitCount >= minDigits,
      hasSpecial: specialCount >= minSpecial,
      hasLength: password.length >= minLength,
      matches: password === confirmPassword && confirmPassword.length > 0
    };

    const isValid = Object.values(checks).every(Boolean);
    setStatus({ ...checks, isValid });

    // Bubble the value and validity up to the parent form
    if (onChange) {
      onChange({
        password,
        isValid
      });
    }
  }, [password, confirmPassword, minUpper, minLower, minDigits, minSpecial, minLength]);

  const toggleVisibility = () => setShowPassword(!showPassword);

  // Helper component to render requirements line by line
  const RequirementItem = ({ reached, text }) => (
    <ListItem disablePadding sx={{ py: 0.25 }}>
      <ListItemIcon sx={{ minWidth: 28 }}>
        {reached ? (
          <CheckCircle color="success" fontSize="small" />
        ) : (
          <Cancel color="error" fontSize="small" />
        )}
      </ListItemIcon>
      <Typography variant="caption" color={reached ? 'success.main' : 'text.secondary'}>
        {text}
      </Typography>
    </ListItem>
  );

  return (
    <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2, width: '100%' }}>
      {/* Primary Password Input */}
      <TextField
        label={labels.password}
        type={showPassword ? 'text' : 'password'}
        value={password}
        onChange={(e) => setPassword(e.target.value)}
        fullWidth
        variant="outlined"
        InputProps={{
          endAdornment: (
            <InputAdornment position="end">
              <IconButton onClick={toggleVisibility} edge="end">
                {showPassword ? <VisibilityOff /> : <Visibility />}
              </IconButton>
            </InputAdornment>
          ),
        }}
      />

      {/* Confirm Password Input */}
      <TextField
        label={labels.confirmPassword}
        type={showPassword ? 'text' : 'password'}
        value={confirmPassword}
        onChange={(e) => setConfirmPassword(e.target.value)}
        fullWidth
        variant="outlined"
        error={confirmPassword.length > 0 && !status.matches}
        helperText={confirmPassword.length > 0 && !status.matches ? "Passwords do not match" : ""}
      />

      {/* Real-time Checklist Checklist */}
      {password.length > 0 && (
        <Box sx={{ bgcolor: 'action.hover', p: 1.5, borderRadius: 1 }}>
          <Typography variant="subtitle2" sx={{ mb: 0.5, fontWeight: 'bold' }}>
            Password Requirements:
          </Typography>
          <List dense disablePadding>
            <RequirementItem reached={status.hasLength} text={`At least ${minLength} characters`} />
            {minUpper > 0 && <RequirementItem reached={status.hasUpper} text={`At least ${minUpper} uppercase letter(s)`} />}
            {minLower > 0 && <RequirementItem reached={status.hasLower} text={`At least ${minLower} lowercase letter(s)`} />}
            {minDigits > 0 && <RequirementItem reached={status.hasDigit} text={`At least ${minDigits} digit(s)`} />}
            {minSpecial > 0 && <RequirementItem reached={status.hasSpecial} text={`At least ${minSpecial} special character(s)`} />}
            <RequirementItem reached={status.matches} text="Passwords match" />
          </List>
        </Box>
      )}
    </Box>
  );
}
